### ISSUE TITLE
Unable to access interactions.

### ISSUE THREAD

**Issue by Senexis** [KartikeSingh/discord-slash-command-handler#2]
Hey there, just a quick bug report. It seems that it's currently not possible to access the interaction in slash commands. This is due to the line below using `message` instead of `interaction`.

https://github.com/KartikeSingh/discord-slash-command-handler/blob/86a28aa53306758687fed2515516e4f907962152/source/classes/handler.ts#L140

**Comment by KartikeSingh** [comment]
Hello @Senexis,
thanks for your report & sorry for late response.

Well that message object is indeed a modified interaction object So in one way we can access it but anyways I will fix it thank you very much 😄
