### ISSUE TITLE
Hey I need help 

### ISSUE THREAD

**Issue by The-dev-collab** [KartikeSingh/discord-slash-command-handler#4]
const discord = require("discord.js");
const figlet = require("figlet"); 
module.exports = {
    name: 'ascii',
    description: 'Makes an ascii ',
    options: [
        {
            name: "Ascii Content",
            description: "Type what you want to covert to ASCII ",
            require: true,
            type: "string"
        }],
    run: async (args,client,Interaction) => {
        let text =  args["Ascii Content"]
        let maxlen = 20
     if(text.length > 20) {
     return Interaction.reply({content: `Please put text that has 20 characters or less because the conversion won't be good!`, ephemeral: true})
     }

     figlet(text, function(err, data) {
        Interaction.reply(data, {
     code: 'AsciiArt' , ephemeral: true,
     });
     })
    }
}

This is my ASCII Command I used the options:[] to get a required option but How can I make let text = to the option named 'Ascii Content'

**Comment by KartikeSingh** [comment]
Hello @The-dev-collab,
1. You can't name your options like that, I mean option's name should be lower case and no spaces

2. to get value of a option just do the following

```js
const as = interaction.options.getString("ascii-content");
// ascii-context should be replaced to options name
// in getString, the String should be replace to option type
```

By the way for more help you can contact me on [discord](https://discord.gg/PBFj276RUw)
my username is `Shisui San#4445`

**Comment by The-dev-collab** [comment]
@KartikeSingh DiscordAPIError: Invalid Form Body
0.options[0].name: Command name is invalid
    at RequestHandler.execute (C:\Users\Zoid\Desktop\Coding\Discord Bots\.JS\ya\node_modules\discord.js\src\rest\RequestHandler.js:350:13)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Zoid\Desktop\Coding\Discord Bots\.JS\ya\node_modules\discord.js\src\rest\RequestHandler.js:51:14)      
    at async ApplicationCommandManager.set (C:\Users\Zoid\Desktop\Coding\Discord Bots\.JS\ya\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18) {
  method: 'put',
  path: '/applications/929078056830779443/commands',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: [
      {
        name: 'ascii',
        description: 'Makes an ascii ',
        type: 1,
        options: [
          {
            type: 3,
            name: 'Ascii-Content',
            description: 'Type what you want to covert to ASCII ',
            required: false,

thats the error I get after doig interaction.options.getsring

**Comment by KartikeSingh** [comment]
bro name should be lowercase
make it `ascii-code`.
