### ISSUE TITLE
Is there any way to delete all the commands deployed with the handler?

### ISSUE THREAD

**Issue by Blixeron** [KartikeSingh/discord-slash-command-handler#5]
Is there any way to delete the deployed commands?

**Comment by KartikeSingh** [comment]
Hello sorry I was out of station, well you can remove global or guild commands manually via
```js
client.application.commands.set([]); // for global commands
client.application.commands.set([],"guild-id"); // for guild commands
```

I might add remove command feature in the handler *soon*
