### ISSUE TITLE
[Enchancement] Using @discord.js/builders

### ISSUE THREAD

**Issue by Stefanuk12** [KartikeSingh/discord-slash-command-handler#6]
Instead of having users manually implement the `options` for Slash Commands, you can use `@discord.js/builders` instead. To convert back to JSON you can call the `.toJSON()` method on the object and grab the `options` property from there.

**Comment by KartikeSingh** [comment]
Good suggestion, I will make this package to use .toJSON if its a builded command else put it normally.

any other suggestions?
