### ISSUE TITLE
Typing Issues

### ISSUE THREAD

**Issue by Stefanuk12** [KartikeSingh/discord-slash-command-handler#7]
The first parameter in `Utils.replyInteraction` accepts only a `CommandInteraction` but whenever it is used within `handler`, the type of the interaction is either `CommandInteraction` or `ContextMenuInteraction`. As a result, it errors.

You need to add type guards in these scenarios.

Currently, the code does not compile.

**Comment by KartikeSingh** [comment]
I see, then I will make it accept a interaction and I think I will just remove this function, cause I used it when discord js 13 was not public (only dev version was available)

Edit: 
1. My bad this replyInteraction function is made according to V-13 my bad, well I will just add all possible types like menu interaction, message component interaction etc, so it won't cause a problem later on.
Also I am closing your previous issue then publish a fix for both issues.
let me know if you have any other problem!

thank you very much for the feedback

**Comment by KartikeSingh** [comment]
Alright, new update is published (3.1.8)!
Please do some testing and let me know if you are facing any issues.
