### ISSUE TITLE
Duplicate Command Creation

### ISSUE THREAD

**Issue by whizbangpop** [KartikeSingh/discord-slash-command-handler#8]
Whenever creating slash commands, the library keep creating a duplicate command.

![image](https://user-images.githubusercontent.com/101482788/168475200-605763d9-c890-408e-9628-f92c977066bc.png)
![image](https://user-images.githubusercontent.com/101482788/168475210-4f896fb8-6a1f-4ba1-a4b2-db7350cab7ae.png)

EDIT: Also, when I delete the duplicate command, it just recreates them.

**Comment by whizbangpop** [comment]
Sorry about this! Looking at it now, it appears to be a Discord client rendering issue.

**Comment by KartikeSingh** [comment]
Alright, well I found some code which can potentially cause a problem like this one, so keeping the issue opened till I publish the fix.
thank you for letting me know about this issue

**Comment by whizbangpop** [comment]
No problem! It does seem to be an issue after doing some more digging.

**Comment by KartikeSingh** [comment]
Alright, new update is published (3.1.8)!
Please do some testing and let me know if you are facing any issues.

**Comment by whizbangpop** [comment]
I've updated to the latest version (3.2.2) and it's now erroring on start:

C:\Users\username\WebstormProjects\project_name\node_modules\discord-slash-command-handler\src\classes\handler.js:68
                        options: this.Utils.fixType(v.type) === 1 ? v.options.toJSON ? v.options.toJSON() : v.options : undefined
                                                                              ^

TypeError: Cannot read properties of undefined (reading 'toJSON')


Not sure if I should open a new issue so thought I would leave it here! I'll have a look and see if I can find the code causing the issue and try fix it.

**Comment by KartikeSingh** [comment]
this is fixed, I should have thought that options is a optional property so it can be undefined, sorry man I think from now on I will try to make dev releases or something before publishing

**Comment by whizbangpop** [comment]
Good news finally! The code isn't erroring and the commands are no longer duplicating!
